dado = input('Digite algo: ')
print('O tipo desse dado é: ',type(dado))
print('Só tem espaços? ', dado.isspace())
print('É Alfa-númerico? ', dado.isalnum())
print('É alfabetico? ', dado.isalpha())
print('É númerico? ', dado.isnumeric())
print('É escrito em caixa baixa? ', dado.islower())
print('É decimal? ', dado.isdecimal())
print('É imprimivel? ', dado.isprintable())
print('É escrito em caixa alta? ', dado.isupper())
print('É um titulo? ', dado.istitle())